//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetMVC1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLPRODUCT
    {
        public int PRODUCTID { get; set; }
        [Required(ErrorMessage ="LÜTFEN ADI GÝRÝNÝZ!")]
        public string PRODUCTAD { get; set; }
        public string SKT { get; set; }
        public Nullable<int> MARKA { get; set; }
        public Nullable<int> ADET { get; set; }
        public string FOTOGRAF { get; set; }
    
        public virtual TBLMARKA TBLMARKA { get; set; }
    }
}
