//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNetMVC1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLTOPTANCI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLTOPTANCI()
        {
            this.TBLMARKA = new HashSet<TBLMARKA>();
        }
    
        public int TOPTANCIID { get; set; }
        [Required(ErrorMessage ="Lütfen Ad giriniz")]
        public string TOPTANCIAD { get; set; }
        [Required(ErrorMessage = "Lütfen SoyAd giriniz")]
        public string TOPTANCISOYAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLMARKA> TBLMARKA { get; set; }
    }
}
